// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjI_TE5-fmB80cBIa8m6tmv3VZPcVHsFE',
    appId: '1:78873146304:ios:249963ba957e127f748e25',
    messagingSenderId: '78873146304',
    projectId: 'ecommerceapp-f7b62',
    databaseURL:
        'https://ecommerceapp-f7b62-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ecommerceapp-f7b62.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjI_TE5-fmB80cBIa8m6tmv3VZPcVHsFE',
    appId: '1:78873146304:ios:249963ba957e127f748e25',
    messagingSenderId: '78873146304',
    projectId: 'ecommerceapp-f7b62',
    databaseURL:
        'https://ecommerceapp-f7b62-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ecommerceapp-f7b62.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARDMKv7mAyus6HpysTeQ7rXa97r0iUQqg',
    appId: '1:78873146304:web:727b1adf90c3c2cc748e25',
    messagingSenderId: '78873146304',
    projectId: 'ecommerceapp-f7b62',
    authDomain: 'ecommerceapp-f7b62.firebaseapp.com',
    databaseURL:
        'https://ecommerceapp-f7b62-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ecommerceapp-f7b62.appspot.com',
    measurementId: 'G-B5V7PWHWBG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwe6GlNE6xGh-Fxvj1UOZ5Avp5zLRMbb0',
    appId: '1:78873146304:android:66a01098e4f2c50c748e25',
    messagingSenderId: '78873146304',
    projectId: 'ecommerceapp-f7b62',
    databaseURL:
        'https://ecommerceapp-f7b62-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ecommerceapp-f7b62.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARDMKv7mAyus6HpysTeQ7rXa97r0iUQqg',
    appId: '1:78873146304:web:f7ed2a36f78b9719748e25',
    messagingSenderId: '78873146304',
    projectId: 'ecommerceapp-f7b62',
    authDomain: 'ecommerceapp-f7b62.firebaseapp.com',
    databaseURL:
        'https://ecommerceapp-f7b62-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ecommerceapp-f7b62.appspot.com',
    measurementId: 'G-15YJLB9S04',
  );
}
